### ISSUE TITLE
Can't alter volcano properties in cam_geom if source already exists, keeps defaulting back to the field in my_sources.txt

### ISSUE THREAD

**Issue by tpering** [twVolc/PyCamPermanent#109]
This happens if information is downloaded from the database, have to go into the my_sources.txt file to delete the record (or alter that record)

Error thrown is here:
![image](https://github.com/twVolc/PyCamPermanent/assets/7857899/331eae22-2e09-4384-a419-ce4da84f4f8f)

**Comment by twVolc** [comment]
Think this is the same as #25?
