### ISSUE TITLE
Image warp error, throws error then stops processing

### ISSUE THREAD

**Issue by tpering** [twVolc/PyCamPermanent#119]
![image](https://github.com/twVolc/PyCamPermanent/assets/7857899/406b8fe3-049d-401f-886d-bd0af9483fc5)

**Comment by tpering** [comment]
Just a further note, this happened midway through processing, closing the software and reopening solved the problem and using different images, think it may have been due to the format of the Clear images used which were not the same as those taken by the camera (generated in Matlab) as these had different sizes

**Comment by twVolc** [comment]
Image registration in general does seem a bit buggy if jumping between different registration types then loading in a new sequence then checking the vignette-corrected image - I'm not sure the exact order of events but I've moved around these options a few times and found that OpenCV registration can sometimes revert back to no registration and vice versa.

**Comment by twVolc** [comment]
@tpering are you happy for me to close this issue, as it sounds like it was less a bug with the software and more an issue with the format of the data? 

I need to open a new issue on general bugginess of image warping, particularly when loading in a new set of images, but think it would make sense to have that as a new issue.

**Comment by tpering** [comment]
Yes, please go ahead and close.

**Comment by twVolc** [comment]
Closing and moving registration bug discussions to #134
