### ISSUE TITLE
flow_nadeau plume speed doesn't update from config

### ISSUE THREAD

**Issue by twVolc** [twVolc/PyCamPermanent#120]
It seems that loading the flow_nadeau plume speed information doesn't correctly update from the config file until you actually open the cross-correlation GUI frame. So if you load a config file then run the processing straight away the processing will be incorrect (i.e. I get strange plume speeds because the nadeau line isn't correctly orientated), but if you load a config file, then open the cross-correlation GUI frame this seems to then load in the nadeau settings and you get totally different flow_nadeau plume speed outputs when running processing again.

**Comment by ubdbra001** [comment]
Digging through this, and it seems to only affect the `nadeau_line_orientation` setting, `nadeau_line_length` seems to update okay for me, though correct me if I'm wrong.
I wonder if it has something to do with the getter for `nadeau_line_orientation` applying a rotation to the value supplied?
https://github.com/twVolc/PyCamPermanent/blob/823f8deea3ad3c4b49a1e9c8201209813151f49b/pycam/gui/figures_analysis.py#L4582-L4591

The value in my config file is -131 and the value in the associated attribute at the start of processing is 311 (which is 180 - (-131)), I think opening up the plot gets the value and so applies a rotation again (180 - 311) , setting it back to -131. Hopefully that makes sense.

**Comment by ubdbra001** [comment]
Yeah, I'm pretty sure that this is the issue. But I think I'll need some more context around what is expected for the GUI and for the backend processing (e.g. does the orientation need to be rotated in both cases?)
