### ISSUE TITLE
Error with pip install

### ISSUE THREAD

**Issue by hcalleja99** [twVolc/PyCamPermanent#131]
Error with installation process appears when initiating “pip install -r requirements.txt” step in conda (I'm working on Windows11), see image below. All previous installation instructions worked as normal. 

![screenshot](https://github.com/twVolc/PyCamPermanent/assets/90771578/cc705357-4966-448f-aae5-75f53177600e)

**Comment by ubdbra001** [comment]
hi @hcalleja99 , thanks for getting in touch.
The thing that jumps out to me from your screenshot is that you appear to be in the base conda environment.
Could you try activating the environment first and then running `pip install -r requirements.txt`?

That may fix it, but if not, post the screenshot/message here. It would also be useful to know which version of PyCam you are using and which version of Python is setup in your conda environment.

**Comment by hcalleja99** [comment]
That now works, thanks @ubdbra001!

**Comment by ubdbra001** [comment]
No problem!
