### ISSUE TITLE
Create parent class for `DoasWorker` and `IfitWorker` that holds common features

### ISSUE THREAD

**Issue by ubdbra001** [twVolc/PyCamPermanent#136]
As title.

**Comment by ubdbra001** [comment]
Some common methods:
`reset_stray_pix()`
`stray_corr_spectra()`

**Comment by twVolc** [comment]
Just to add, in reality, the vast majority of methods in these classes should be duplicates - I just haven't managed to keep on top of maintaining DOASWorker to a useable state. In an ideal world really the only method that would differ across the two is `process_doas()` and then also some related helper methods that might do things inside `process_doas()`. Also the light dilution correction aspects are reliant on iFit, so these won't be present in DOASWorker. Beyond these two big areas there should be a huge amount of common ground in the classes.
