### ISSUE TITLE
Save optical depth time-series

### ISSUE THREAD

**Issue by twVolc** [twVolc/PyCamPermanent#14]
Save time series of optical depths taken from the camera (in the spectrometer's field of view). These can then be combined with the spectrometer column density time series at any time to look at calibration lines.

**Comment by twVolc** [comment]
Just a note to where this is currently found in pycam. `tau` in `PyplisWorker.update_doas_calibration()` is one place where it's extracted - its extracted using the lines (line 2096-2099):

```
# Extract values from current image
bool_array = np.array(doas_fov.fov_mask_rel, dtype=bool)
tau_fov = img_tau.img[bool_array]
tau = tau_fov.mean()]
``` 

This will have been taken directly from pyplis somewhere. This is passed to `PyplisWorker.add_doas_cal_data`, where I can see that the vector we want is `self.calib_pears.tau_vec` (this is a pyplis object and will be generated earlier on - typical during `PyplisWorker.doas_fov_search()`. The key issue is this vector is continually updated to only contain a user defined period of data - we want to save the entire series (alongside the timestamp), so we will just need a way of doing this.

Note, if the DOAS field of view (FOV) is fixed in the GUI (i.e. `PyplisWorker.doas_fov_search()` won't be run because we are manually providing the DOS FOV), `PyplisWorker.doas_fov_search()` won't ever be run, so would need to account for this in how the tau data points are saved. I imagine saving to a permanent vector within `PyplisWorker.add_doas_cal_data` is the way to go in general, but we need to be aware that when the DOAS FOV search is run, the initial x minutes of data will be dervied from within `PyplisWorker.doas_fov_search()` and won't pass through `PyplisWorker.add_doas_cal_data` (I think....).

More exploration needed!

**Comment by ubdbra001** [comment]
I had a bit of a poke around the code you highlighted and I _think_ that past Tom has done us a massive favour by creating the `add_doas_cal_data()` function (on line 2178), that seems to update `self.calib_pears.tau_vec` with each new tau value.
I'm having a play around to make sure that this is the case, but this may be a relatively strightforward thing to implement.

**Comment by twVolc** [comment]
Yes in most cases this should work perfectly, the only part I'm worried about is the initial `doas_fov_search()` - prior to knowing the FOV of the camera (e.g. typically the first 30 - 45ish minutes of data - user-defined value) optical depths from the camera won't be extracted - because we don't yet know where the spectrometer is looking within the camera image. So after `line 1964` which calls a pyplis method `self.calib_pears = s.perform_fov_search(method='pearson')`, I think the initial `self.calib_pears.tau_vec` is automatically generated from that method so will need extracting somewhere there as it won't pass through `add_doas_cal_data()`. Does that make sense? I might be wrong about these things by the way, I haven't had an in-depth look, but it's how logically I imagine things are working.

**Comment by twVolc** [comment]
Note - probably important in case we've overlooked this so far - the `rem_doas_cal_data()` method will also be removing data points from `self.calib_pears.tau_vec` sequentially - just thought I'd add this point in case you were thinking we will just be able to save `self.calib_pears.tau_vec` at the end of processing. I think instead we'll need to create our own array that holds the full dataset - rather than directly messing with/editing `self.calib_pears.tau_vec`

**Comment by ubdbra001** [comment]
> I think the initial self.calib_pears.tau_vec is automatically generated from that method so will need extracting somewhere there as it won't pass through add_doas_cal_data()

It techincally does pass through the function as, unless I'm misunderstanding, the `add_doas_cal_data()` just appends the latest value to this vector.
But, I hadn't seen `rem_doas_cal_data()`. That makes life a bit tricker.

So the two options I see are:
1. Create a copy of this initial vector and adjust the `add_doas_cal_data()` so it writes the new values to this copied vector.
2. Replace `rem_doas_cal_data()` with a function that selects a subset of the tau/cd values rather than removing values (e.g for a 30 min winfow it always gets the last 360 values)

What do you think?
For me option 1 is easier to do. Option 2 is neater (you're not duplicating vectors) but would require a bit more work with a higher chance of messing something up.

**Comment by twVolc** [comment]
Yes the `add_doas_cal_data()` will eventually be executed in a processing thread, but the first 30 or so minutes, and the initial generation of `self.calib_pears.tau_vec` occurs outside of this function, so I think I see what you mean - the first time `add_doas_cal_data()` is executed within the processing thread, we will know that's the point at which `tau_vec` up to that point has already been generated and contains 30 or so minutes of data. But note, if we used a fixed DOAS FOV that isn't the case as in that case `doas_fov_search()` is never run and the `tau_vec` generation begins with the `add_doas_cal_data()` method, i think. Basically it's just requires a small bit of thought to ensure we don't duplicate data when writing optical depths to our new variable.

I think I'd go with Option 1 as `self.calib_pears` is a pyplis object that requires the specific subset of the full optical depth time series (i.e. `self.calib_pears.tau_vec` needs to be the cut version as it is used directly in calibration), so I think we'd end up also having to change pyplis code if we didn't keep this as a subset.

**Comment by ubdbra001** [comment]
So I have had an initial attempt at implimenting option 1 and have a vector that is 1021 values in length. The list of images in 1023, so it doesn't match exactly.
Does this seem like a reasonable value to you?

**Comment by twVolc** [comment]
That sounds pretty good. There's a chance that it will always be 1 short as we can only generate 1 emission rate data point for 2 separate image pairs, since we need to also calculate a plume speed using 2 pairs of images at different times. Where exactly this all occurs in the pipeline I can't remember exactly, as we can generate optical depth (tau) images for every time-step so should be able to generate 1023 optical depth points if there are 1023 pairs of images, but perhaps on of those is never extracted as it is not used in the final emission rate calculations. Why we would be 2 short rather than 1 short is a little less clear to me. I guess the way to see is to extract the timestamps alongside the optical depths, which we will need anyway for the optical depths to be meaningful, and see what timestamps are missing relative to the image pairs we have.
