### ISSUE TITLE
If going from processing a high concentration day in the DOAS window the Figure y axis does not reset

### ISSUE THREAD

**Issue by tpering** [twVolc/PyCamPermanent#153]
If you are processing DOAS data, and say one day of data has very high concentrations (~10,000 ppm) and you then load in another day the y axis does not reset (as in the below). This could be relevant for real-time-processing if we are going from day-to-day of data, i.e., may need a reset on a new day.

![image](https://github.com/twVolc/PyCamPermanent/assets/7857899/7717b986-e298-430f-a581-bfbf2875b641)

**Comment by twVolc** [comment]
Closing as fixed by PR #186
