### ISSUE TITLE
doas_results processing parameters txt file does not update light dilution correction value used

### ISSUE THREAD

**Issue by tpering** [twVolc/PyCamPermanent#154]
As above, the processing file does not update the light dilution correction factor used (have confirmed that data has been corrected with factor). 

See here:

![image](https://github.com/twVolc/PyCamPermanent/assets/7857899/285f4cfc-9d71-4953-93d7-1e22f352195e)

**Comment by twVolc** [comment]
Light dilution correction in this case is a boolean relating to if this processing procedure used the full light dilution correction algorithm (i.e. did it perform the entire LDF calculation procedure for each spectrum). So having it set to 0 in this case should be correct. When setting the LDF manually like I think you have, this value should still be displayed in the doas_results file output under the LDF column - when set manually that LDF will just be the same in every row of the file.

**Comment by tpering** [comment]
Gotcha, might be more accurate if this was either "true" or "false" or "true-static" or similar?

**Comment by twVolc** [comment]
Edited the line to say:
`Light dilution correction used (on/off)=` 
for some clarity. This has been edited in Dev.
