### ISSUE TITLE
Issue with config file on load-up, dark spectra directory issue? Program won't load.

### ISSUE THREAD

**Issue by tpering** [twVolc/PyCamPermanent#157]
After changing the default loading config file, I get the following error, it seems to do with setting the Dark spectra directory? I have to manually revert the config file to the default to get it to load up again:

![image](https://github.com/twVolc/PyCamPermanent/assets/7857899/8858a235-b858-479a-b12f-413b5d7689bc)

Note that after this, I can then load in the config file successfully and all parameters have been set properly.

**Comment by twVolc** [comment]
Could you attach the config file you used to get this error? It looks like it's a DOAS FOV error of some sort I think

**Comment by tpering** [comment]
.yml not uploadable, doc instead 

[Error_yml.docx](https://github.com/user-attachments/files/15904149/Error_yml.docx)

**Comment by tpering** [comment]
Note, I just received a similar error for a config file with the error "couldn't find ILS location" even though ILS location exists (and available)

![image](https://github.com/twVolc/PyCamPermanent/assets/7857899/c5eccfa9-9783-4f2f-9436-2169f0c06103)

**Comment by tpering** [comment]
I have changed the flag to priority on this as this seems to be a repeat issue which means that it isn't possible to set a default config, as below:

![WhatsApp Image 2024-07-23 at 03 58 50](https://github.com/user-attachments/assets/68c101c4-5737-4aa5-a6cc-c55f2e5fbbde)

**Comment by twVolc** [comment]
Closing as fix has been merged to Dev branch
