### ISSUE TITLE
Generate calibration fit statistics

### ISSUE THREAD

**Issue by twVolc** [twVolc/PyCamPermanent#16]
Some statistics for calibration (column density vs optical depth) need to be generated (plotted and saved) so that the quality of the fit can be generated. Poor quality fits might suggest SO2 camera images are affected by clouds or there are other issues with the retrieval. Such statistics could therefore form the basis for rejecting/ignoring poor quality data,so is an important step for fully-automating data analysis.

**Comment by twVolc** [comment]
Current functionality from the above commit needs improving.
> It will only work properly with 1st order polynomial fits.
 
> Plots update iteratively even when not requested to do so. I think this really slows down processing as the fit stats time series gets quite big.

**Comment by ubdbra001** [comment]
> ...I think to close the issue it would be nice to have these statistics plotted in the GUI whilst processing is running - so that real-time evaluation of these parameters is possible. I did start this in pycam.gui.figures_analysis.DOASFOVSearchFrame() and its fig_cal_params attribute and within its update_plot method. But i didn't ever get it working properly. I think with the arrays you've now generated it should be relatively straightforward to start displaying these parameters within the GUI?

From https://github.com/twVolc/PyCamPermanent/pull/44#issuecomment-1623592021

**Comment by ubdbra001** [comment]
Just to confirm, the panel indicated below is where you'd like the fit statistics plotted:
![image](https://github.com/twVolc/PyCamPermanent/assets/18421270/8cba0e82-410d-413a-9a23-026d8488356e)

Should it be the coefficient for the slope and R squared on the two y-axes?
Should I worry about polynomial regression here or is that somehting to think about later?

**Comment by twVolc** [comment]
Sorry yes I think if you can change the fit error to r-squared would be easier to interpret. We've also just discussed that a legend would be very useful! (My bad). 

I think for now we can ignore issues with second order polynomials for this plot, as probably getting meaningful info from it would be difficult - unless you can think of an obvious way to do this? 

Rearranging the format of this part of the GUI, perhaps so the time series is along the entire bottom, so it's easier to read as it gets longer, would be useful too. But this is probably an enhancement that maybe needs it's own non-priority issue to be opened.

**Comment by ubdbra001** [comment]
Okay, great. I think I've got it and will put in apull request this afternoon.
I was thinking of colouring the labels for each of the y-axes so that they correspond to the colour of the associated points. That way the information is communicated, but without taking up additional space on the plot.

Not sure how to acheive this off of the top of my head, but I can have a think for a future fix.

Yes, add this as an issue and I'll think about how to do this.
