### ISSUE TITLE
Data don't seem to be displayed during RTP

### ISSUE THREAD

**Issue by twVolc** [twVolc/PyCamPermanent#165]
Just tried the RTP branch and the images don't seem to be displayed in the GUI unless you then tcik "Display only mode". i.e. the images themselves aren't showing up in the GUI even though we can see that they are being found by the RTP procedure - this is printed to the console.

**Comment by tpering** [comment]
Just to note that this seems to be erratic, for instance, this is currently working for the analysis and camera window:

![image](https://github.com/twVolc/PyCamPermanent/assets/7857899/5a41e171-634a-4776-883c-ea2b565a309a)

**Comment by tpering** [comment]
[process_config - Copy.txt](https://github.com/user-attachments/files/16177123/process_config.-.Copy.txt)

Attached config file that works for displaying data

**Comment by twVolc** [comment]
I think this is now fixed in the RTP branch and will work after PR #143

**Comment by ubdbra001** [comment]
I haven't done anything specific to fix this in #143, so I'm a little suspicious of it working now.
Did you do something to fix it @twVolc?

**Comment by twVolc** [comment]
I don't remember doing anything but I'm pretty certain you did this as a first fix when we checked RTP and realised the images coming in weren't being displayed? I think you hadn't realised we wanted the GUI updating during RTP? Images and everything are now definitely all updating in Merapi and have been from the start, so at some point it was definitely fixed.

**Comment by twVolc** [comment]
@ubdbra001 We've just been discussing this - in the lab we were checking the watch directory functionality whereas here in Merapi we're using data transfer RTP. Could it be that the data transfer case is working and images are correctly being displayed but perhaps the issue does still exist when just watching a directory? I can't see why this would be the case as both cases are using the same underlying `PyplisWorker` methods for directory watching and data processing, so should perform identically other than one not having FTP transfer going on in the background. Unless there's something I've missed or misunderstood about your implementation of the watch directory stuff?

**Comment by ubdbra001** [comment]
> @ubdbra001 We've just been discussing this - in the lab we were checking the watch directory functionality whereas here in Merapi we're using data transfer RTP. Could it be that the data transfer case is working and images are correctly being displayed but perhaps the issue does still exist when just watching a directory? I can't see why this would be the case as both cases are using the same underlying `PyplisWorker` methods for directory watching and data processing, so should perform identically other than one not having FTP transfer going on in the background. Unless there's something I've missed or misunderstood about your implementation of the watch directory stuff?

There is a chance that this inadvertently got fixed in one of the changes I made for the directory watcher branch, but I'm more inclined to believe that this may be why. I'll play around with it once 169 is done.

**Comment by ubdbra001** [comment]
I've had a change to look at this, and I think it is working correctly.
I have the 'Plot iteratively' checkbox set and when watching the data come in (not ftp) it updates the images (the pairs and the subtracted), the doas time series, and the emission plots.
It looks like it's behaving the same as the ftp transfer, so you may be correct that this is working.

Do have a go with it yourselves and see if it's doing/showing what you expect.

**Comment by twVolc** [comment]
Closing this as I think we're all confident/happy that daa are now displayed when RTP is running.
