### ISSUE TITLE
Enhancement - automated production of video for calibrated SO2 image (with a ppm scale)

### ISSUE THREAD

**Issue by tpering** [twVolc/PyCamPermanent#174]
As above, perhaps in the Save > Options section it would be useful to be able to combine saved SO2 png's with a scale (as per the analysis window) into a video on output. 

It would also be nice to be able to set the image colour used for the normal SO2 images saved (as per the analysis window, i.e., the seismic output shows really nice definition).

**Comment by twVolc** [comment]
Haven't done this as a video, but this has been implemented as saving the SO2 image figure. Videos should be created manually by combining the images in some other software (not PyCam). This solution seems suitable for RTP and general functionality of this software, users might be interested in having specific images available for display online for example.
