### ISSUE TITLE
flux file in RTP mode isn't produced

### ISSUE THREAD

**Issue by alfabimsakti** [twVolc/PyCamPermanent#177]
After RTP runs all day, processed data folder has been made but the flux file isn't produced. The folder is also made in the wrong directory, in this case, 2024-07-23 processed folder is made on 2024-07-22 image folder. 

See the screenshot
![Screenshot 2024-07-23 100736](https://github.com/user-attachments/assets/b622e859-74a6-4377-9e07-f31277f3a5de)

**Comment by twVolc** [comment]
Solved the issue:

The `PyplisWorker.results_ready()` check was checking all flow types, regardless of if we had all flow types ticked for processing (we've currently been testing things just with flow_histo). Within the `results_ready()` method I have changed
```res_ready = all([len(res.start_acq) > 0 for res in curr_results.values()])```
to
```res_ready = all([len(curr_results[key].start_acq) > 0 for key in curr_results if self.velo_modes[key]])```
This means we only check if we have results for the flow types that are `True`.

I haven't updated this anywhere other than directly onto the Merapi computer, so @ubdbra001 if you can make this change and push to your RTP branch that would be good, or I can look at doing this later.

**Comment by twVolc** [comment]
Will be fixed in #143 so closing issue
