### ISSUE TITLE
Add functionality for Nadeau plume speed algorithm 

### ISSUE THREAD

**Issue by twVolc** [twVolc/PyCamPermanent#20]
Nadeau suggests a different plume speed algorithm which can give image-by-image resolution for plume speeds but using cross correlation. It involves cross correlating a single line profile in successive images - the profile is parallel to plume transport direction, rather than perpendicular. The main issue here would be ensuring the line is in the correct location/orientation, as the plume direction can change quite significantly in short time-scales. Some kind of automated process for drawing this line could work - e.g. using the gas source location and the location of the bulk plume relative to this.

**Comment by tpering** [comment]
Could use the average phi angle output (i.e. -80 degrees) and use the position of the source to draw a line along the plume.

**Comment by twVolc** [comment]
This was added in #76, so should be available on master soon. Further updates might be needed to make it run smoothly and the GUI work perfectly in all scenarios, but I think I'll close this as it's at least completed to a useable level
