### ISSUE TITLE
numpy.ndarray has no attribute 'meta'

### ISSUE THREAD

**Issue by ubdbra001** [twVolc/PyCamPermanent#21]
![image](https://github.com/twVolc/PyCamPermanent/assets/18421270/b829cdeb-bc9b-49bf-9db5-9a815f263d1f)
> Got an error during calibration and kicked me off software. I then try and run_pycam.py again and it is still stuck on the error.

![image](https://github.com/twVolc/PyCamPermanent/assets/18421270/c282aeaa-0c8f-486d-8d6d-06f7bda9d3a5)
> Another bug on startup

**Comment by twVolc** [comment]
It seems I duplicated this in #157 and fixed it in #185.
