### ISSUE TITLE
Simple one - install instructions needs extra line

### ISSUE THREAD

**Issue by tpering** [twVolc/PyCamPermanent#35]
Need to change this instruction to include:

Install dependencies from the requirements.txt file:
**cd PyCamPermenant**
pip install -r requirements.txt

**Comment by tpering** [comment]
Obviously with the correct spelling...

**Comment by twVolc** [comment]
I think it has this line further up - straight after the `git clone ...`, so should be all good?

**Comment by tpering** [comment]
Oh yeah...nevermind
