### ISSUE TITLE
Move from g/s to kg/s

### ISSUE THREAD

**Issue by twVolc** [twVolc/PyCamPermanent#36]
Pyplis emission rate outputs are in g/s by default. I have no idea why this is but I just kept it as-is when saving data in pycam (although note that the emission rate plot in the GUI is in kg/s). kg/s is just a much more readable value and is in SI units so we really should move everything to kg/s. The units should also be saved in the final output files - I believe they currently are not.

**Comment by ubdbra001** [comment]
Out of interest, do you remember why you create a new instance of the `EmissionRates` object here, rather than:
https://github.com/twVolc/PyCamPermanent/blob/823f8deea3ad3c4b49a1e9c8201209813151f49b/pycam/io_py.py#L382-L392

Is it so the results can be filtered by `indices`?

**Comment by twVolc** [comment]
I honestly have no idea what I'm doing here. I'm guessing I half followed pyplis examples and maybe half hacked my own solution to get things to work, but it's probably not as efficient as it could be.

**Comment by ubdbra001** [comment]
Okay, I've rewritten it to just leverage pandas to do everything. Will submit a PR shortly.

**Comment by twVolc** [comment]
Sounds great. This is presumably also where things get broken up into hour-long chunks to save, whereas I think we've discussed saving each day in its entirety together is more suitable, so I'm guessing this function eventually can be stripped down quite a bit. Not sure if that's already an issue or not.

**Comment by twVolc** [comment]
Also just to say, I'm not sure where the g/s comes in here exactly, but it's probably worth hunting for the exact location that the emission rate is first given in g/s and removing the conversion there - then the whole program will be running in kg/s rather than solely converting to kg/s when saving the text files. This would involve ensuring where the emission rates are plotted in the GUI they aren't then scaled again so that we aren't inadvertently working with values x1000 bigger than we think

**Comment by ubdbra001** [comment]
> Sounds great. This is presumably also where things get broken up into hour-long chunks to save, whereas I think we've discussed saving each day in its entirety together is more suitable, so I'm guessing this function eventually can be stripped down quite a bit. Not sure if that's already an issue or not.

Yep, I was going to make an issue for it and make a note that this is where it happens (so I don't forget).

> Also just to say, I'm not sure where the g/s comes in here exactly, but it's probably worth hunting for the exact location that the emission rate is first given in g/s and removing the conversion there - then the whole program will be running in kg/s rather than solely converting to kg/s when saving the text files. This would involve ensuring where the emission rates are plotted in the GUI they aren't then scaled again so that we aren't inadvertently working with values x1000 bigger than we think

I did that, the data is generated from `pyplis.fluxcalc` from the `det_emission_rate()` function. I did originally consider changing it there, but that function is called in 6 different places (all in `calculate_emission_rate() within `so2_camera_processor.py`).
I wanted to spend a bit more time with the code to see how similar the code in these different places is, and maybe reduce it into a single function.

I'm also not 100% sure how the plots have kg/s. I suspect the values are still g/s but the x-axis is scaled and just has a kg/s label. So, I didn't want to break anything there by changing the source of the values yet.

I think it would still be worth keeping this issue open so I can return to it and maybe correct the underlying data.

**Comment by twVolc** [comment]
> I did that, the data is generated from `pyplis.fluxcalc` from the `det_emission_rate()` function. I did originally consider changing it there, but that function is called in 6 different places (all in `calculate_emission_rate() within `so2_camera_processor.py`).
> I wanted to spend a bit more time with the code to see how similar the code in these different places is, and maybe reduce it into a single function.

Ok great. I'd definitely stick to changining it in `so2_camera_processor.py` wherever it comes out from `pyplis`, rather than in `pyplis`. But yeh, where exactly that needs to be you'll know better than me now!




> I'm also not 100% sure how the plots have kg/s. I suspect the values are still g/s but the x-axis is scaled and just has a kg/s label. So, I didn't want to break anything there by changing the source of the values yet.

I think this will just be the GUI dividing emission rates by 1000 prior to plotting the results. It will be somewhere in `figures_analysis.py`. I'm on a new computer at the moment and still going through pycham installation, so can't quickly check sorry! I think it will only be one place as it's only plotted in the one time series figure in the GUI, so once this is found adn the emission rates are edited to kg/s at source everything should be correct.

**Comment by ubdbra001** [comment]
> I think this will just be the GUI dividing emission rates by 1000 prior to plotting the results. It will be somewhere in `figures_analysis.py`. I'm on a new computer at the moment and still going through pycham installation, so can't quickly check sorry! I think it will only be one place as it's only plotted in the one time series figure in the GUI, so once this is found adn the emission rates are edited to kg/s at source everything should be correct.

I did have a look through the `figures_analysis.py` code and found where the plot is updated:
https://github.com/twVolc/PyCamPermanent/blob/823f8deea3ad3c4b49a1e9c8201209813151f49b/pycam/gui/figures_analysis.py#L1248-L1258

I couldn't see anywhere obvious before or after that the units are changed, hence my suspicion that it's actually just the scaling. But I'll take another look.

**Comment by twVolc** [comment]
Ah 

> I couldn't see anywhere obvious before or after that the units are changed, hence my suspicion that it's actually just y-axis (not x-axis) scaling. But I'll take another look.

Ah yes you're right! In that case I wonder if `pyplis` actually scales to kg/s in its plot function?? As I think that plot call is to a method of one of the `pyplis` objects. I guess this complicates things slightly as if that's the case and we scale emission rates to kg/s prior to plotting, that plot method may divide by 1000 again so display the wrong units. Maybe the plot method has an option to say what units the data are in, otherwise maybe it's just easier to plot the time series directly ourselves rather than using the pyplis method?

**Comment by ubdbra001** [comment]
Yep, that's it. The plot method has the default option of plotting in kg/s:
https://github.com/jgliss/pyplis/blob/178f8195e08decb5f3ca26018b23893e313ec217/pyplis/fluxcalc.py#L648-L649

Okay, so if I change the source of the values to kg/s then I can switch that flag to false, and we should be all good 🤞
