### ISSUE TITLE
Light dilution correction of spectrometer throws error

### ISSUE THREAD

**Issue by tpering** [twVolc/PyCamPermanent#42]
The following error:

![WhatsApp Image 2023-06-29 at 10 43 56](https://github.com/twVolc/PyCamPermanent/assets/7857899/8290d25a-cc95-4991-aeb4-23953381bc74)

Used these files:

[Error.zip](https://github.com/twVolc/PyCamPermanent/files/11904595/Error.zip)

**Comment by twVolc** [comment]
Quick fix - a few people seem to have an issue with `shapely.speedups`. Disabling this make the processing work with that data.

In `pycam.ifit_ld.lookup.py` add the lines to the import section:
```
import shapely
shapely.speedups.disable()
```

I'm not sure how this will affect #22, so perhaps I'll keep this issue open for now. But will push this change to the dev branch now.

**Comment by twVolc** [comment]
Actually I'm closing this as we can see this issue linked in #22, so if we ever come to migrating we'll be aware of what I've done here. It seems we've fixed this issue at least.
