### ISSUE TITLE
Fixing FOV - not certain radius is in correct units

### ISSUE THREAD

**Issue by twVolc** [twVolc/PyCamPermanent#43]
When fixing the FOV of the spectrometer (instead of calculating it by correlating with the optical-depth image stack), I'm not certain that the radius works correctly - i.e. is fixing the radius reproducing exactly the same results as if pyplis calculated the radius. I have a feeling it's possible pyplis units for radius are different to the GUI's (e.g. degrees vs pixels) so we might be causing errors if using the fixed radius option.

To test we would need to compare the optical depth time series for the fixed FOV and for the calibrated/correlated FOV (that uses the pyplis FOV search function). They should be identical if all other processing remains the same.

**Comment by tpering** [comment]
During real-time processing, this will need to be fixed, i.e., we don't want to spend computational time searching for a FOV.

**Comment by twVolc** [comment]
Details on how the FOV is initially generated (and therefore how the parameters are stored) can be found in `PyplisWorker.doas_fov_search` `line 1955` in `master` branch. I believe the FOV data are stored in the pyplis `DoasCalibData` object (in particular probably `DoasCalibData.fov` so it should be as simple as editing specific attributes in there. I think my main current concern is I didn't adequately test this and I think the pycam GUI's FOV definitions (specifically the radius units) might not correctly map to the pyplis FOV units - this is really what needs checking. Note I've only allowed circular FOV definitions - pyplis does allow eliptical FOVs but I think it's unlikely to make a huge difference to the results considering all the other uncertainties involved so sticking to the simpler circular FOV is fine.

**Comment by twVolc** [comment]
Sorry, to sumarise this more succinctly - basically what you should be able to do is set the exact same FOV pixel coordinates and radius as found using the FOV search and get exactly the same calibration data (and thus emission rate time series) out as a result.

**Comment by twVolc** [comment]
I'm not sure the code actually even runs when fixing the FOV at the moment. So this might need more than just getting units right

**Comment by twVolc** [comment]
That sounds like a pretty significant different - as in 1.648 times larger? I would guess it might be the radius that is getting incorrectly defined, as the centres coordinate should be really simple (I hope), it's just the x and y positions of the FOV. 

Rather than comparing the emission rates (although this is totally valid as it should by extension match up) it might be worth comparing the optical depths extracted from the camera images - that are saved in the full calibration file. These should be identical if the fixed FOV is accurately recreating what the FOV search finds (but we'll give a little leeway for the fact there's a chance the FOV search could find an eliptical shape FOV, I think, whereas the fixed FOV we are always just defining a circular FOV. 

I think the units are g/s in the saved files, unless we have edited this? It's kg/s in the plots - there's an issue #36 related to the fact it saves in g/s rather than kg/s, but maybe this has been fixed?

**Comment by twVolc** [comment]
> with a range of 0.165-7.934.

I should say that if you're getting emission rates like this then we've almost certainly already shifted to kg/s

**Comment by tpering** [comment]
It might be helpful to compare the two emission rates from (1) and (2)
directly side by side?

**Comment by ubdbra001** [comment]
> It might be helpful to compare the two emission rates from (1) and (2) directly side by side?
Here's a sample of the emission rates data (Happy to post the full file if you think it would be useful)

![image](https://github.com/twVolc/PyCamPermanent/assets/18421270/f81e1d6b-792f-4f97-8b7a-11d5f3799756)

This is for the flow_raw, _phi_x is (1) and _phi_y is (2). The rest of the columns (_velo_eff, etc) have identical values for the two options.

**Comment by twVolc** [comment]
Yeh a very tiny different, but I would feel more comfortable if we could get the optical depths identical before merging this, as that should be possible if we are truly reproducing the FOV. I think it the radius size that is almost certainly the issue

**Comment by twVolc** [comment]
> self.doas_fov_extent = self.calib_pears.fov.pixel_extend(abs_coords=True)

Actually I think this just returns the coordinates of the extent of the FOV, so it doesn't change anything. Basically I guess the aim is to get the output of this extent to be exactly the same as if we fix the FOV

**Comment by twVolc** [comment]
Just as extra info: I looked into it a little more and I think the line `s.g2dasym = False  # Allow only circular FOV (not eliptical) ` only comes into play if the fov search `method='ifr'`, so even if this were set incorrectly I'm pretty confident we would always have a circular FOV with `method='pearson'`.

**Comment by ubdbra001** [comment]
Okay I had a poke around in the `DoasFOV` object, and noticed a few differences:

1. This is the object after the `doas_fov_search`:
![image](https://github.com/twVolc/PyCamPermanent/assets/18421270/531f8401-59ce-4260-b327-b887a7be396f)

2. This is the one created at the start of a fix_fov processing run:
![image](https://github.com/twVolc/PyCamPermanent/assets/18421270/d4e914a6-316c-4de8-a471-75f600fb364d)

A few differences between the objects jump out here, any idea if any of these would have an impact?
- (2) appears to have a Camera object as an attribute
- The `x_abs` and `y_abs` values are different
- The `sigma_x_abs` and `sigma_y_abs` values are different
- The `pyrlevel` values are different

I've made pkls of these objects if you'd like to inspect them yourself.

**Comment by twVolc** [comment]
Ok, so the `pyrlevel` is the amount of subsampling taking place in the image I believe. So `pyrlevel=0` means no subsampling - our images have the dimensions 486 x 648. `pyrlevel=1` means the object believes that the images are being downsampled to 243 x 324, so when the relative x and y values are being set `cx_rel` and `cy_rel` `pyplis` is then convertin this to absolute coordinates by projecting those coordinates onto a ful resolution image - so `x_abs` and `y_abs` are double `cx_rel` and `cy_rel`. This is my current thinking anyway. `Line 2316` in `so2_camera_processor` sets this, and I'm guessing I ust incorrectly set `pyrlevel` thinking that 1 meant no subsampling. If you change this to 0 hopefully it will help things, automatically fixing `x_abs` and `y_abs`, and looking at how `sigma_x_abs` and `sigma_y_abs`  are caluculated I think this will automatically get them correct too (I've got no idea what these parameters do...)

I'm amazed that the emission rates seem to come out so similar if the coordinates are so drastically different, so I wonder if the calibration uses `cx_rel` and `cy_rel` rather than `x_abs` and `y_abs`, so you may find this changes absolutely nothing in the output, but definitely worth getting this right - maybe the `sigmas` have a small affect that could be accounting for our slight differences...

**Comment by twVolc** [comment]
> So for `fix_fov` you are correct the camera is set, it's not set for the `doas_fov_search`. I'm going to try unsetting it to see if it makes a difference.

Ah, that's probably why it always throws a warning saying no camera is set at the start of the FOV search. I wonder if we should work out why it isn't set and set it. Again, it probably won't make a difference, so it's slightly confusing that we aren't getting exactly the same results. 

I think checking `fov_extend` might be important, as I think this defines the extent of the fov. In `so2_camera_processor` there's 2 important places:
-  `line 2318` - the FOV mask is manually generated
- `line 2406` - the mask is used to extract the optical depth

**Comment by twVolc** [comment]
> Another thought I had after looking at the calibration data is that the weird thing where some timepoints are skipped/not skipped may play a role, by slightly altering the regression coefficients for the two calibration methods.
> 
> Here is a snapshot of the full_calibration files side by side (left side is for `doas_fov_search` and right is for `fix_fov`: ![image](https://private-user-images.githubusercontent.com/18421270/289027292-66891f2f-8b1d-4dce-bf1d-2c556bfb5071.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDIwMjg5NDYsIm5iZiI6MTcwMjAyODY0NiwicGF0aCI6Ii8xODQyMTI3MC8yODkwMjcyOTItNjY4OTFmMmYtOGIxZC00ZGNlLWJmMWQtMmM1NTZiZmI1MDcxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjA4VDA5NDQwNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTNmNzM1MDhiZDFhMmE0ZTM1OTMxMDVlZGRjYTBjNThjYjhhYjc5ZjM3ZTUzMzVmNjUwNjRhNGQzMTE4MzVhZjkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.LvNe-PEJI_3DbsF5GGN3KgYCK4PGFlXV8X6c--zyq40)
> 
> They are identical until row 356, and then there are two differences:
> 
> * The coefficients from the regression are included earlier in `doas_fov_search` (they should be going from the same time right?)
> * There are two missing timepoints in `doas_fov_search`, 16:35:10 and 16:35:15
> 
> My understanding of the calibration is that it uses the correlation coefficients to adjsut the pixel values of the image, and then the emission rate is estimated from these adjusted values. So, if the data being used for the correlation is slightly different between the two calibration approaches then the coefficients will be different, and the resulting adjustments and emission rates will be different. Is my grasp of that correct?

Ah yes, this will be the problem then! So the DOAS FOV is being correctly defined, which is good. But for some reason we are missing some data points when using the DOAS FOV search so that puts everything out ever so slightly? So actually the fixed FOV is working better than the search now... I'm I right in thinking this relates to another issue that you've raised a few times?

**Comment by ubdbra001** [comment]
Possibly, though I'm not entirely sure how.
I've made some notes in #73, but effectively: when using the Preloaded calibration option, there are 3 additional time points included in the emission rate data. Two of which correspond to the points being dropped here (which will be around when the `doas_fov_search` is run.

**Comment by twVolc** [comment]
I'd guess it's something simple to do with indexing when looping back through the old data once the FOV has been found, but then why it's new data 5 minutes later that's dropped I have no idea. I'm not quite sure how they then turn up in the preloaded calibration though as that suggests they must have been calculated and saved in the array in the first place?

**Comment by ubdbra001** [comment]
> Ah, that's probably why it always throws a warning saying no camera is set at the start of the FOV search. I wonder if we should work out why it isn't set and set it. Again, it probably won't make a difference, so it's slightly confusing that we aren't getting exactly the same results.

As predicted, this doesn't make a difference.

**Comment by ubdbra001** [comment]
Possibly silly question, but I'm assuming that you'd like the `fix_fov` params values (e.g. x, y, rad) generated by `doas_fov_search` to be included in the output config?
GIven that the config file is produced at the start of the run, would it be worth updating the config as soon as `doas_fov_search` has finished?

**Comment by twVolc** [comment]
Yeh that would be great, and yes it seems like a sensible time to update it right after the FOV search has successfully found the coordinates.

In terms of loading things back in, it looks like some of the variables currently aren't in `DOASFOVSearchFrame.vars` and also they don't have the correct names relative to `PyplisWorker`. So I guess there might be a bit of thinking/editing there, but presumably it's the same as the stuff you've previously done when setting up the config files in the first place.
