### ISSUE TITLE
FTP Watch Directory Error

### ISSUE THREAD

**Issue by tpering** [twVolc/PyCamPermanent#51]
We click Start Transfer (New Images) and the following error crops up:
![image](https://github.com/twVolc/PyCamPermanent/assets/7857899/1bb3d43b-fca0-4fcd-a08b-f66e7e541c17)

**Comment by twVolc** [comment]
This should be fixed now but I seem to remember we had a similar issue a few months ago that you fixed @ubdbra001? So think I'll just keep the issue open now for this discussion - do you remember this and can you think why it may have come back, or if it's totally different. I just want to make sure it isn't somehow recurring to make sure it doesn't happen again... e.g. I'm wondering if the package might be version-dependent as to whether it works for our application or not.

**Comment by ubdbra001** [comment]
From what I remember this error only cropped up last time as I was using python `3.9`, not `3.8`. As how the dependecies were resolved seemed to be slightly different for the two different versions.
If this happened with `3.8` then making `pywin32` an explicit dependency is probably the best move.

**Comment by twVolc** [comment]
Ah yes that rings a bell, I had forgotten that this compatibility was the reason for sticking with python 3.8! I'll close this now then as it should now be fixed on dev branch at least.
