### ISSUE TITLE
Compare and merge current docs into a master doc

### ISSUE THREAD

**Issue by ubdbra001** [twVolc/PyCamPermanent#7]
Pull the two current docs together into a single doc.

Should be able to pull both into markdown format using [pandoc](https://pandoc.org/), in prep for making a version available alongside the repo

**Comment by tpering** [comment]
We could probably close this issue? We have documentation available here, could point towards that on the GitHub page? https://www.volcanotech.org/software.html

**Comment by tpering** [comment]
I have closed this issue, I added a link to documentation on the github page straight to master, trying to tidy a little, hope ok
